name: Build Visual Module

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  checks:
    uses: bellflight/github-actions/.github/workflows/avr_build_and_push_container.yml@main
    with:
      container_name: visual
      platforms: linux/arm64