name: Python Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    uses: nathanvaughn/AVR-github-actions/.github/workflows/avr_python_tests.yml@main